# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_layout_attemptSplitter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1190, 649)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../.designer/backup/resources/icon_windows.ico"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralized = QtWidgets.QWidget(MainWindow)
        self.centralized.setObjectName("centralized")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralized)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.centralized)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_all = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_all.setGeometry(
            QtCore.QRect(0, 0, 1190, 629)
        )
        self.scrollAreaWidgetContents_all.setObjectName(
            "scrollAreaWidgetContents_all"
        )
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents_all
        )
        self.verticalLayout.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hl_controlbar = QtWidgets.QHBoxLayout()
        self.hl_controlbar.setContentsMargins(5, -1, 5, -1)
        self.hl_controlbar.setObjectName("hl_controlbar")
        self.grid_loads = QtWidgets.QGridLayout()
        self.grid_loads.setObjectName("grid_loads")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_all)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.grid_loads.addWidget(self.line_2, 1, 0, 1, 2)
        self.pb_load_images = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pb_load_images.sizePolicy().hasHeightForWidth()
        )
        self.pb_load_images.setSizePolicy(sizePolicy)
        self.pb_load_images.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pb_load_images.setObjectName("pb_load_images")
        self.grid_loads.addWidget(self.pb_load_images, 0, 0, 1, 1)
        self.pb_load_rods = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pb_load_rods.sizePolicy().hasHeightForWidth()
        )
        self.pb_load_rods.setSizePolicy(sizePolicy)
        self.pb_load_rods.setObjectName("pb_load_rods")
        self.grid_loads.addWidget(self.pb_load_rods, 2, 0, 1, 1)
        self.le_image_dir = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.le_image_dir.sizePolicy().hasHeightForWidth()
        )
        self.le_image_dir.setSizePolicy(sizePolicy)
        self.le_image_dir.setMinimumSize(QtCore.QSize(100, 0))
        self.le_image_dir.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_image_dir.setObjectName("le_image_dir")
        self.grid_loads.addWidget(self.le_image_dir, 0, 1, 1, 1)
        self.le_rod_dir = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.le_rod_dir.sizePolicy().hasHeightForWidth()
        )
        self.le_rod_dir.setSizePolicy(sizePolicy)
        self.le_rod_dir.setMinimumSize(QtCore.QSize(100, 0))
        self.le_rod_dir.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_rod_dir.setObjectName("le_rod_dir")
        self.grid_loads.addWidget(self.le_rod_dir, 2, 1, 1, 1)
        self.hl_controlbar.addLayout(self.grid_loads)
        spacerItem = QtWidgets.QSpacerItem(
            13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.hl_controlbar.addItem(spacerItem)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_all)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.hl_controlbar.addWidget(self.line_3)
        spacerItem1 = QtWidgets.QSpacerItem(
            13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.hl_controlbar.addItem(spacerItem1)
        self.group_disp_method = QtWidgets.QGroupBox(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.group_disp_method.sizePolicy().hasHeightForWidth()
        )
        self.group_disp_method.setSizePolicy(sizePolicy)
        self.group_disp_method.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter
        )
        self.group_disp_method.setObjectName("group_disp_method")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_disp_method)
        self.verticalLayout_4.setContentsMargins(0, 0, -1, 4)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_disp_all = QtWidgets.QRadioButton(self.group_disp_method)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.rb_disp_all.sizePolicy().hasHeightForWidth()
        )
        self.rb_disp_all.setSizePolicy(sizePolicy)
        self.rb_disp_all.setChecked(False)
        self.rb_disp_all.setObjectName("rb_disp_all")
        self.verticalLayout_4.addWidget(self.rb_disp_all)
        self.rb_disp_class = QtWidgets.QRadioButton(self.group_disp_method)
        self.rb_disp_class.setChecked(True)
        self.rb_disp_class.setObjectName("rb_disp_class")
        self.verticalLayout_4.addWidget(self.rb_disp_class)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rb_disp_one = QtWidgets.QRadioButton(self.group_disp_method)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.rb_disp_one.sizePolicy().hasHeightForWidth()
        )
        self.rb_disp_one.setSizePolicy(sizePolicy)
        self.rb_disp_one.setMinimumSize(QtCore.QSize(70, 0))
        self.rb_disp_one.setObjectName("rb_disp_one")
        self.horizontalLayout_3.addWidget(self.rb_disp_one)
        self.le_disp_one = QtWidgets.QLineEdit(self.group_disp_method)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.le_disp_one.sizePolicy().hasHeightForWidth()
        )
        self.le_disp_one.setSizePolicy(sizePolicy)
        self.le_disp_one.setMaximumSize(QtCore.QSize(40, 16777215))
        self.le_disp_one.setObjectName("le_disp_one")
        self.horizontalLayout_3.addWidget(self.le_disp_one)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.rb_disp_none = QtWidgets.QRadioButton(self.group_disp_method)
        self.rb_disp_none.setObjectName("rb_disp_none")
        self.verticalLayout_4.addWidget(self.rb_disp_none)
        self.hl_controlbar.addWidget(self.group_disp_method)
        spacerItem2 = QtWidgets.QSpacerItem(
            13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.hl_controlbar.addItem(spacerItem2)
        self.group_rod_color = QtWidgets.QGroupBox(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.group_rod_color.sizePolicy().hasHeightForWidth()
        )
        self.group_rod_color.setSizePolicy(sizePolicy)
        self.group_rod_color.setAlignment(QtCore.Qt.AlignCenter)
        self.group_rod_color.setObjectName("group_rod_color")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_rod_color)
        self.gridLayout_4.setContentsMargins(0, 0, -1, 4)
        self.gridLayout_4.setHorizontalSpacing(4)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rb_class1 = QtWidgets.QRadioButton(self.group_rod_color)
        self.rb_class1.setObjectName("rb_class1")
        self.gridLayout_4.addWidget(self.rb_class1, 1, 1, 1, 1)
        self.rb_class3 = QtWidgets.QRadioButton(self.group_rod_color)
        self.rb_class3.setObjectName("rb_class3")
        self.gridLayout_4.addWidget(self.rb_class3, 3, 1, 1, 1)
        self.rb_class2 = QtWidgets.QRadioButton(self.group_rod_color)
        self.rb_class2.setObjectName("rb_class2")
        self.gridLayout_4.addWidget(self.rb_class2, 2, 1, 1, 1)
        self.rb_class0 = QtWidgets.QRadioButton(self.group_rod_color)
        self.rb_class0.setChecked(True)
        self.rb_class0.setObjectName("rb_class0")
        self.gridLayout_4.addWidget(self.rb_class0, 0, 1, 1, 1)
        self.hl_controlbar.addWidget(self.group_rod_color)
        spacerItem3 = QtWidgets.QSpacerItem(
            13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.hl_controlbar.addItem(spacerItem3)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_all)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.hl_controlbar.addWidget(self.line_4)
        spacerItem4 = QtWidgets.QSpacerItem(
            13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.hl_controlbar.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_frame_disp = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.le_frame_disp.sizePolicy().hasHeightForWidth()
        )
        self.le_frame_disp.setSizePolicy(sizePolicy)
        self.le_frame_disp.setStyleSheet(
            "background-color: transparent;font-weight: bold;"
        )
        self.le_frame_disp.setFrame(False)
        self.le_frame_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.le_frame_disp.setReadOnly(True)
        self.le_frame_disp.setPlaceholderText("")
        self.le_frame_disp.setObjectName("le_frame_disp")
        self.verticalLayout_2.addWidget(self.le_frame_disp)
        self.le_rod_disp = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.le_rod_disp.sizePolicy().hasHeightForWidth()
        )
        self.le_rod_disp.setSizePolicy(sizePolicy)
        self.le_rod_disp.setStyleSheet(
            "background-color: transparent; font-weight: bold;"
        )
        self.le_rod_disp.setFrame(False)
        self.le_rod_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.le_rod_disp.setReadOnly(True)
        self.le_rod_disp.setPlaceholderText("")
        self.le_rod_disp.setObjectName("le_rod_disp")
        self.verticalLayout_2.addWidget(self.le_rod_disp)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_previous = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pb_previous.sizePolicy().hasHeightForWidth()
        )
        self.pb_previous.setSizePolicy(sizePolicy)
        self.pb_previous.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pb_previous.setObjectName("pb_previous")
        self.horizontalLayout.addWidget(self.pb_previous)
        spacerItem5 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Preferred,
            QtWidgets.QSizePolicy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem5)
        self.pb_next = QtWidgets.QPushButton(self.scrollAreaWidgetContents_all)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pb_next.sizePolicy().hasHeightForWidth()
        )
        self.pb_next.setSizePolicy(sizePolicy)
        self.pb_next.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pb_next.setObjectName("pb_next")
        self.horizontalLayout.addWidget(self.pb_next)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.slider_frames = QtWidgets.QSlider(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.slider_frames.sizePolicy().hasHeightForWidth()
        )
        self.slider_frames.setSizePolicy(sizePolicy)
        self.slider_frames.setOrientation(QtCore.Qt.Horizontal)
        self.slider_frames.setObjectName("slider_frames")
        self.verticalLayout_2.addWidget(self.slider_frames)
        self.hl_controlbar.addLayout(self.verticalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(
            13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.hl_controlbar.addItem(spacerItem6)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_all)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.hl_controlbar.addWidget(self.line_5)
        spacerItem7 = QtWidgets.QSpacerItem(
            10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.hl_controlbar.addItem(spacerItem7)
        self.grid_save = QtWidgets.QGridLayout()
        self.grid_save.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.grid_save.setObjectName("grid_save")
        self.le_save_dir = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.le_save_dir.sizePolicy().hasHeightForWidth()
        )
        self.le_save_dir.setSizePolicy(sizePolicy)
        self.le_save_dir.setMinimumSize(QtCore.QSize(100, 0))
        self.le_save_dir.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_save_dir.setObjectName("le_save_dir")
        self.grid_save.addWidget(self.le_save_dir, 0, 1, 1, 1)
        self.pb_save_rods = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents_all
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pb_save_rods.sizePolicy().hasHeightForWidth()
        )
        self.pb_save_rods.setSizePolicy(sizePolicy)
        self.pb_save_rods.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pb_save_rods.setObjectName("pb_save_rods")
        self.grid_save.addWidget(self.pb_save_rods, 0, 0, 1, 1)
        self.hl_controlbar.addLayout(self.grid_save)
        self.verticalLayout.addLayout(self.hl_controlbar)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_all)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.camera_tabs = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.camera_tabs.sizePolicy().hasHeightForWidth()
        )
        self.camera_tabs.setSizePolicy(sizePolicy)
        self.camera_tabs.setStyleSheet(
            "QTabWidget#camera_tabs{font-weight: bold;}"
        )
        self.camera_tabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.camera_tabs.setObjectName("camera_tabs")
        self.right_tabs = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.right_tabs.sizePolicy().hasHeightForWidth()
        )
        self.right_tabs.setSizePolicy(sizePolicy)
        self.right_tabs.setAutoFillBackground(True)
        self.right_tabs.setStyleSheet(
            " QTabWidget#right_tabs{font-weight: bold;}"
        )
        self.right_tabs.setTabPosition(QtWidgets.QTabWidget.East)
        self.right_tabs.setObjectName("right_tabs")
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_all)
        self.verticalLayout_7.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralized)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1190, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setEnabled(True)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_docs = QtWidgets.QMenu(self.menuHelp)
        self.menu_docs.setObjectName("menu_docs")
        MainWindow.setMenuBar(self.menubar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setEnabled(True)
        self.action_save.setObjectName("action_save")
        self.action_zoom_in = QtWidgets.QAction(MainWindow)
        self.action_zoom_in.setObjectName("action_zoom_in")
        self.action_zoom_out = QtWidgets.QAction(MainWindow)
        self.action_zoom_out.setObjectName("action_zoom_out")
        self.action_original_size = QtWidgets.QAction(MainWindow)
        self.action_original_size.setObjectName("action_original_size")
        self.action_fit_to_window = QtWidgets.QAction(MainWindow)
        self.action_fit_to_window.setEnabled(True)
        self.action_fit_to_window.setObjectName("action_fit_to_window")
        self.action_persistent_view = QtWidgets.QAction(MainWindow)
        self.action_persistent_view.setCheckable(True)
        self.action_persistent_view.setChecked(True)
        self.action_persistent_view.setObjectName("action_persistent_view")
        self.action_revert = QtWidgets.QAction(MainWindow)
        self.action_revert.setObjectName("action_revert")
        self.action_redo = QtWidgets.QAction(MainWindow)
        self.action_redo.setEnabled(True)
        self.action_redo.setObjectName("action_redo")
        self.action_cleanup = QtWidgets.QAction(MainWindow)
        self.action_cleanup.setObjectName("action_cleanup")
        self.action_open_rods = QtWidgets.QAction(MainWindow)
        self.action_open_rods.setObjectName("action_open_rods")
        self.action_preferences = QtWidgets.QAction(MainWindow)
        self.action_preferences.setObjectName("action_preferences")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_about_qt = QtWidgets.QAction(MainWindow)
        self.action_about_qt.setObjectName("action_about_qt")
        self.action_shorten_selected = QtWidgets.QAction(MainWindow)
        self.action_shorten_selected.setShortcutContext(
            QtCore.Qt.WidgetShortcut
        )
        self.action_shorten_selected.setObjectName("action_shorten_selected")
        self.action_lengthen_selected = QtWidgets.QAction(MainWindow)
        self.action_lengthen_selected.setShortcutContext(
            QtCore.Qt.WidgetShortcut
        )
        self.action_lengthen_selected.setObjectName("action_lengthen_selected")
        self.action_shorten_displayed = QtWidgets.QAction(MainWindow)
        self.action_shorten_displayed.setObjectName("action_shorten_displayed")
        self.action_lengthen_displayed = QtWidgets.QAction(MainWindow)
        self.action_lengthen_displayed.setObjectName(
            "action_lengthen_displayed"
        )
        self.action_logs = QtWidgets.QAction(MainWindow)
        self.action_logs.setObjectName("action_logs")
        self.action_autoselect_rods = QtWidgets.QAction(MainWindow)
        self.action_autoselect_rods.setCheckable(True)
        self.action_autoselect_rods.setChecked(True)
        self.action_autoselect_rods.setObjectName("action_autoselect_rods")
        self.action_bug_report = QtWidgets.QAction(MainWindow)
        self.action_bug_report.setObjectName("action_bug_report")
        self.action_feature_request = QtWidgets.QAction(MainWindow)
        self.action_feature_request.setObjectName("action_feature_request")
        self.action_docs_local = QtWidgets.QAction(MainWindow)
        self.action_docs_local.setObjectName("action_docs_local")
        self.action_docs_online = QtWidgets.QAction(MainWindow)
        self.action_docs_online.setObjectName("action_docs_online")
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_save)
        self.menuEdit.addAction(self.action_revert)
        self.menuEdit.addAction(self.action_redo)
        self.menuView.addAction(self.action_zoom_in)
        self.menuView.addAction(self.action_zoom_out)
        self.menuView.addAction(self.action_original_size)
        self.menuView.addAction(self.action_fit_to_window)
        self.menu_docs.addAction(self.action_docs_local)
        self.menu_docs.addAction(self.action_docs_online)
        self.menuHelp.addAction(self.action_logs)
        self.menuHelp.addAction(self.menu_docs.menuAction())
        self.menuHelp.addAction(self.action_about)
        self.menuHelp.addAction(self.action_about_qt)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_bug_report)
        self.menuHelp.addAction(self.action_feature_request)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.camera_tabs.setCurrentIndex(-1)
        self.right_tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RodTracker"))
        self.pb_load_images.setText(_translate("MainWindow", "Load Images"))
        self.pb_load_rods.setText(_translate("MainWindow", "Load Particles"))
        self.group_disp_method.setTitle(
            _translate("MainWindow", "Display Methods")
        )
        self.rb_disp_all.setText(_translate("MainWindow", "All Particles"))
        self.rb_disp_class.setText(_translate("MainWindow", "Selected Class"))
        self.rb_disp_one.setText(_translate("MainWindow", "Particle No.:"))
        self.rb_disp_none.setText(_translate("MainWindow", "None"))
        self.group_rod_color.setTitle(
            _translate("MainWindow", "Particle Class")
        )
        self.rb_class1.setText(_translate("MainWindow", "Class1"))
        self.rb_class3.setText(_translate("MainWindow", "Class3"))
        self.rb_class2.setText(_translate("MainWindow", "Class2"))
        self.rb_class0.setText(_translate("MainWindow", "Class0"))
        self.le_frame_disp.setText(_translate("MainWindow", "Frame: ???"))
        self.le_rod_disp.setText(
            _translate("MainWindow", "Loaded Particles: 0")
        )
        self.pb_previous.setToolTip(_translate("MainWindow", "Previous Image"))
        self.pb_previous.setText(_translate("MainWindow", "Previous"))
        self.pb_previous.setShortcut(_translate("MainWindow", "Left"))
        self.pb_next.setToolTip(_translate("MainWindow", "Next Image"))
        self.pb_next.setText(_translate("MainWindow", "Next"))
        self.pb_next.setShortcut(_translate("MainWindow", "Right"))
        self.pb_save_rods.setText(_translate("MainWindow", "Save"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menu_docs.setTitle(_translate("MainWindow", "Documentation"))
        self.action_open.setText(_translate("MainWindow", "Open Images"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_zoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.action_zoom_in.setShortcut(_translate("MainWindow", "+"))
        self.action_zoom_out.setText(_translate("MainWindow", "Zoom out"))
        self.action_zoom_out.setShortcut(_translate("MainWindow", "-"))
        self.action_original_size.setText(
            _translate("MainWindow", "Original Size")
        )
        self.action_original_size.setShortcut(
            _translate("MainWindow", "Ctrl+R")
        )
        self.action_fit_to_window.setText(
            _translate("MainWindow", "Fit to Window")
        )
        self.action_persistent_view.setText(
            _translate("MainWindow", "Persistent View")
        )
        self.action_revert.setText(_translate("MainWindow", "Undo"))
        self.action_revert.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_redo.setText(_translate("MainWindow", "Redo"))
        self.action_redo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.action_cleanup.setText(_translate("MainWindow", "Cleanup Data"))
        self.action_open_rods.setText(
            _translate("MainWindow", "Open Rod Data")
        )
        self.action_preferences.setText(
            _translate("MainWindow", "Preferences")
        )
        self.action_about.setText(_translate("MainWindow", "About"))
        self.action_about_qt.setText(_translate("MainWindow", "About Qt"))
        self.action_shorten_selected.setText(
            _translate("MainWindow", "Shorten Selected Rod")
        )
        self.action_shorten_selected.setShortcut(_translate("MainWindow", "S"))
        self.action_lengthen_selected.setText(
            _translate("MainWindow", "Lengthen Selected Rod")
        )
        self.action_lengthen_selected.setShortcut(
            _translate("MainWindow", "A")
        )
        self.action_shorten_displayed.setText(
            _translate("MainWindow", "Shorten Displayed Rods")
        )
        self.action_shorten_displayed.setShortcut(
            _translate("MainWindow", "T")
        )
        self.action_lengthen_displayed.setText(
            _translate("MainWindow", "Lengthen Displayed Rods")
        )
        self.action_lengthen_displayed.setShortcut(
            _translate("MainWindow", "R")
        )
        self.action_logs.setText(_translate("MainWindow", "Show Logs"))
        self.action_autoselect_rods.setText(
            _translate("MainWindow", "Autoselect rods")
        )
        self.action_autoselect_rods.setShortcut(_translate("MainWindow", "G"))
        self.action_bug_report.setText(
            _translate("MainWindow", "Report a BUG")
        )
        self.action_feature_request.setText(
            _translate("MainWindow", "Request a FEATURE")
        )
        self.action_docs_local.setText(_translate("MainWindow", "Local"))
        self.action_docs_online.setText(_translate("MainWindow", "Online"))
