DATASETS:
  TEST: []
  TRAIN: []
INPUT:
  CROP:
    SIZE:
    - 512
    - 512
  MAX_SIZE_TEST: 1280
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 960
  MIN_SIZE_TRAIN:
    - 960
MODEL:
  ANCHOR_GENERATOR:
    ASPECT_RATIOS:
    - - 0.5
      - 1.0
      - 2.0
    SIZES:
    - - 16
      - 24
      - 36
      - 48
      - 60
  BACKBONE:
    NAME: build_resnet_fpn_backbone
  FPN:
    IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
  KEYPOINT_ON: true
  META_ARCHITECTURE: GeneralizedRCNN
  PIXEL_MEAN:
  - 152.0
  - 152.0
  - 144.0
  RESNETS:
    DEPTH: 101
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 2
  ROI_BOX_HEAD:
    NAME: FastRCNNConvFCHead
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    SMOOTH_L1_BETA: 0.5
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    NAME: StandardROIHeads
    NUM_CLASSES: 1
  ROI_MASK_HEAD:
    NAME: MaskRCNNConvUpsampleHead
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  RPN:
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    - p6
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1500
    PRE_NMS_TOPK_TEST: 1000
    PRE_NMS_TOPK_TRAIN: 2000
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
SOLVER:
  BASE_LR: 0.02
  IMS_PER_BATCH: 16
  MAX_ITER: 270000
  STEPS: (210000, 250000)
TEST:
  DETECTIONS_PER_IMAGE: 210
VERSION: 2
